### PR TITLE
Fixed poor PDF resolution at initial preview on Android

### LINKED ISSUE #32: Poor PDF resolution at initial preview
Hi,

I've got an issue with PDF resolution on Android. Initial preview is blurry but then when I'm zooming it's ok.
This [StackOverflow post](https://stackoverflow.com/a/32327174) shows how to improve PDF resolution.

Based on this post, I produced this patch using patch-package lib:

```diff
diff --git a/node_modules/react-native-pdf-renderer/android/src/main/java/com/github/douglasjunior/reactNativePdfRenderer/modules/PdfRendererRecyclerView.java b/node_modules/react-native-pdf-renderer/android/src/main/java/com/github/douglasjunior/reactNativePdfRenderer/modules/PdfRendererRecyclerView.java
index 0c5a515..04a7568 100644
--- a/node_modules/react-native-pdf-renderer/android/src/main/java/com/github/douglasjunior/reactNativePdfRenderer/modules/PdfRendererRecyclerView.java
+++ b/node_modules/react-native-pdf-renderer/android/src/main/java/com/github/douglasjunior/reactNativePdfRenderer/modules/PdfRendererRecyclerView.java
@@ -412,9 +414,9 @@ public class PdfRendererRecyclerView extends RecyclerView {
             public void update(int position, float newZoom) {
                 var page = mPdfRenderer.openPage(position);
                 var bitmap = Bitmap.createBitmap(
-                        Math.round(page.getWidth() * newZoom),
-                        Math.round(page.getHeight() * newZoom),
-                        Bitmap.Config.ARGB_4444
+                    Math.round((getResources().getDisplayMetrics().densityDpi * page.getWidth() / 72) * newZoom),
+                    Math.round((getResources().getDisplayMetrics().densityDpi * page.getHeight() / 72) * newZoom),
+                    Bitmap.Config.ARGB_8888
                 );
                 page.render(bitmap, null, null, PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);
```

You can see the difference before and after the patch:

Screenshot_20241217-105955_Evolution Mobile
Screenshot_20241217-110137_Evolution Mobile

My sample PDF:
[simple.pdf](https://github.com/user-attachments/files/18163740/simple.pdf)

### PR DESCRIPTION
**Pull request by rmarquois**
Fixes #32

### CODE REVIEW

File: android/src/main/java/com/github/douglasjunior/reactNativePdfRenderer/modules/PdfRendererRecyclerView.java [hunk 1]
```diff
@@ -419,8 +419,8 @@ public ImageView getImageView() {
             }
 
             private @NonNull Bitmap createBitmap(float newZoom, int pageWidth, int pageHeight) {
-                var scaledPageWidth = Math.round(pageWidth * newZoom);
-                var scaledPageHeight = Math.round(pageHeight * newZoom);
+                var scaledPageWidth = Math.round(getResources().getDisplayMetrics().densityDpi * pageWidth * newZoom / 72);
```
Comment (douglasjunior) [inline android/src/main/java/com/github/douglasjunior/reactNativePdfRenderer/modules/PdfRendererRecyclerView.java:422]: Please, just add a comment with the link for the explanation to this formula.

Example:

```suggestion
                // Calculate the size to match PDF rendering quality with a high-DPI screen 
                // https://stackoverflow.com/a/32327174/2826279
                var scaledPageWidth = Math.round(getResources().getDisplayMetrics().densityDpi * pageWidth * newZoom / 72);
```

**Review by douglasjunior — CHANGES_REQUESTED** [review]
Thank you for the pull request! 🙏 

Please add a reference to the formula used to calculate the size.

**Review by douglasjunior — APPROVED** [review]
LGTM
